---
title: "Testing Log-Density Emulators for VSEM Inverse Problem"
output: html_document
---

```{r}
set.seed(543653)

library(data.table)
library(ggplot2)
library(patchwork)
library(scales)
library(grid)
library(support)

experiment_tag <- "vsem"
write_plots <- FALSE

# base_dir <- file.path("/Users/andrewroberts/Desktop/git-repos/bip-surrogates-paper")
# code_dir <- file.path("/Users/andrewroberts/Desktop/git-repos/gp-calibration")
base_dir <- file.path("/projectnb", "dietzelab", "arober", "bip-surrogates-paper")
code_dir <- file.path("/projectnb", "dietzelab", "arober", "gp-calibration")
src_dir <- file.path(code_dir, "src")
experiment_dir <- file.path(base_dir, "experiments", experiment_tag)
out_dir <- file.path(experiment_dir, "output", "inv_prob_setup")
alg_settings_dir <- file.path(experiment_dir, "output", "alg_settings")
plt_dir <- file.path(out_dir, "plots")

# Source required files.
source(file.path(src_dir, "general_helper_functions.r"))
source(file.path(src_dir, "statistical_helper_functions.r"))
source(file.path(src_dir, "inv_prob_test_functions.r"))
source(file.path(src_dir, "plotting_helper_functions.r"))
source(file.path(src_dir, "mcmc_helper_functions.r"))
source(file.path(src_dir, "seq_design.r"))
source(file.path(src_dir, "gp_helper_functions.r"))
source(file.path(src_dir, "gp_mcmc_functions.r"))
source(file.path(src_dir, "gpWrapper.r"))
source(file.path(src_dir, "llikEmulator.r"))
source(file.path(src_dir, "seq_design.r"))
source(file.path(src_dir, "seq_design_gp.r"))
source(file.path(src_dir, "seq_design_for_post_approx.r"))
source(file.path(base_dir, "scripts", "helper", "sim_study_functions.r"))
source(file.path(base_dir, "..", "sipnet_calibration", "src", "prob_dists.r"))
source(file.path(base_dir, "..", "sipnet_calibration", "src", "eki_pecan.r"))
```

```{r}
# Read data/plots saved to file.
samp_dt <- fread(file.path(out_dir, "samp_exact.csv"))
samp_dt_prior <- fread(file.path(out_dir, "prior_samp.csv"))
inv_prob <- readRDS(file.path(out_dir, "inv_prob_list.rds"))
test_info_prior <- readRDS(file.path(out_dir, "test_info_prior.rds"))
test_info_post <- readRDS(file.path(out_dir, "test_info_post.rds"))
em_settings <- readRDS(file.path(alg_settings_dir, "em_settings.rds"))
design_settings <- readRDS(file.path(alg_settings_dir, "init_design_settings.rds"))

par_prior <- inv_prob$par_prior_trunc
lprior <- get_lprior_dens(par_prior)
prior_list <- convert_par_info_to_list(par_prior)
par_maps <- get_par_map_funcs(prior_list)
llik_obj <- inv_prob$llik_obj
llik <- function(U) llik_obj$assemble_llik(U)

lpost <- function(U) {
  if(is.null(dim(U))) U <- matrix(U, nrow=1L)
  lprior(U) + llik(U)
}
```

```{r}
# log prior, likelihood and posterior as function of transformed/unconstrained variables.
lprior_phi <- function(phi) {
  par <- par_maps$inv(phi)
  log_det_J <- attr(par, "log_det_J")
  
  lprior(par) + log_det_J
}

# Adjust llik to account for parameter transformation.
llik_phi <- function(phi, ...) {
  llik(par_maps$inv(phi), ...)
}

# Log-unnormalized posterior density as function of transformed parameter.
lpost_phi <- function(phi) lprior_phi(phi) + llik_phi(phi)
```


# Investigate structure of the true log-likelihood/log-posterior.
```{r}
# Prepare points for plotting projections.
pad_bounds <- get_prior_bounds(par_prior, tail_prob_excluded=0.000001)
prior_bounds <- get_prior_bounds(par_prior, set_hard_bounds=TRUE)
prior_bounds[,1:2] <- pad_bounds[,1:2]
prior_bounds[1,3:4] <- pad_bounds[1,3:4]

fixed_vals <- sample_prior(par_prior, n=10L)
input_grids <- get_input_grid_1d_projection(inv_prob$par_names, 
                                            X_fixed=fixed_vals,
                                            X_bounds=prior_bounds, 
                                            n_points_default=300L)

# In transformed space.
input_grids_phi <- list()
for(i in seq_along(input_grids)) {
  par_name <- names(input_grids)[i]
  input_grids_phi[[par_name]] <- list()
  
  for(j in seq_along(input_grids[[i]])) {
    input_grids_phi[[par_name]][[j]] <- par_maps$fwd(input_grids[[par_name]][[j]])
  }
}

names(input_grids_phi) <- colnames(input_grids_phi[[1]][[1]])
```

```{r}
# 1d projections in original space.
proj_llik_plots <- plot_1d_proj(llik, input_grids=input_grids)
proj_lpost_plots <- plot_1d_proj(lpost, input_grids=input_grids)

# 1d projections in transformed/unconstrained space.
proj_llik_plots_phi <- plot_1d_proj(llik_phi, input_grids=input_grids_phi)
proj_lpost_plots_phi <- plot_1d_proj(lpost_phi, input_grids=input_grids_phi)
```


```{r}
for(plt in proj_llik_plots) plot(plt)
```

```{r}
for(plt in proj_lpost_plots) plot(plt)
```

```{r}
for(plt in proj_llik_plots_phi) plot(plt)
```

```{r}
for(plt in proj_lpost_plots_phi) plot(plt)
```

# Initial design and emulator fit.
```{r}
design <- design_settings$lhs_extrap(inv_prob, n=500L)
lpost_em <- em_settings$em_lpost_twostage$fit_em(design, inv_prob)
```

```{r}
# Predictions at prior and posterior points.
lpost_scatter_prior <- lpost_em$plot_pred_validation(test_info_prior$input, 
                                                     adjustment="rectified",
                                                     true_llik=test_info_prior$lpost, 
                                                     interval_method="CI", CI_prob=0.9)
lpost_scatter_post <- lpost_em$plot_pred_validation(test_info_post$input,
                                                    adjustment="rectified",
                                                    true_llik=test_info_post$lpost, 
                                                    interval_method="CI", CI_prob=0.9)

# Format plots.
lpost_scatter_prior <- ggformat_journal(lpost_scatter_prior, remove_title=TRUE)
lpost_scatter_post <- ggformat_journal(lpost_scatter_post, remove_title=TRUE)

plot(lpost_scatter_prior)
plot(lpost_scatter_post)

if(write_plots) {
  ggsave(file.path(plt_dir, "pred_scatter_prior_lpostem.png"), lpost_scatter_prior)
  ggsave(file.path(plt_dir, "pred_scatter_post_lpostem.png"), lpost_scatter_post)
}

# lpost_scatter_prior +
#   annotate("label", x=-2000, y=0, label="rmse: 10\ncrps: 5\nlog-score: 4",
#             hjust=0, vjust=1, label.size=0.3, label.r=unit(0.2, "lines"),
#             size=8)
```
```{r}
bounds <- inv_prob$llik_obj$get_llik_bounds()[2] + test_info_post$lprior
samp <- lpost_em$sample(test_info_post$input, N_samp=10000, adjustment="none")
for(i in 1:10000) {
  samp[,i] <- pmin(samp[,i], bounds)
}

preds <- matrixStats::rowLogSumExps(samp) - log(ncol(samp))

plot(test_info_post$lpost, preds)
abline(a=0, b=1, col="red")
```







```{r}
# Looking out farther in the tails.
# TODO: need to make sure `fixed_vals` satisfies prior bounds.

# Values exactly at the bound currently results in NAs due to parameter
# transformations.
prior_bounds_eps <- prior_bounds
prior_bounds_eps[1,] <- prior_bounds_eps[1,] + 1e-8 
prior_bounds_eps[2,] <- prior_bounds_eps[2,] - 1e-8

input_grids <- get_input_grid_1d_projection(inv_prob$par_names, 
                                            X_fixed=fixed_vals,
                                            X_bounds=prior_bounds_eps, 
                                            n_points_default=300L)

# Plot one-dimensional projections of log-posterior density emulator (on log scale).
lpost_em_quantile <- function(U) {
  llik_em$calc_quantiles(U, p=0.95, adjustment="rectified") + lprior(U)
}

lpost_em_extrap_plots <- plot_1d_proj(lpost_em_quantile, input_grids=input_grids)

# Plot one-dimensional projections of posterior density emulator (on log scale).
# TODO: what is going on with Cv-fixed2 around Cv in [10,15]. Quantile is flat.
# post_em_extrap_plots <- lpost_em$plot_1d_proj_approx_lik(input_grids=input_grids2, 
#                                                          approx_type="quantile",
#                                                          alpha=0.9, 
#                                                          adjustment="rectified")

design_bounds <- get_bounds(llik_em$get_design_inputs())

for(i in seq_along(lpost_em_extrap_plots)) {
  par_name <- names(lpost_em_extrap_plots)[i]
  design_bounds_par <- design_bounds[,par_name]
  plt <- lpost_em_extrap_plots[[i]] + 
          geom_vline(xintercept=design_bounds_par[1], color="grey", linetype="dashed", linewidth=2) +
          geom_vline(xintercept=design_bounds_par[2], color="grey", linetype="dashed", linewidth=2) +
          labs(y="Quantile")
  plt <- ggformat_journal(plt, remove_title=TRUE)
  plot(plt)
  
  if(write_plots) {
    ggsave(file.path(plt_dir, paste0("extrap_q95_lpostem_", par_name, ".png")), plt)
  }
}

```

# Posterior Approximation
```{r}
# MCMC settings.
cov_prop_init <- cov(design_comb$input)
n_chains <- 4L

# mcwmh-joint.
mcmc_settings <- list(test_label="mcwmh-joint", 
                      mcmc_func_name="mcmc_noisy_llik", llik_em=lpost_em,
                      par_prior=par_prior_trunc, mode="mcwmh", use_joint=TRUE, 
                      n_avg=10L, n_itr=20000L, itr_start=10000, n_chain=n_chains, 
                      try_parallel=TRUE, cov_prop=cov_prop_init, adjustment="rectified")
mcmc_approx_mcwmh <- do.call(run_mcmc_chains, mcmc_settings)
samp_dt_mcwmh <- mcmc_approx_mcwmh$samp

# expected likelihood.
mcmc_settings <- list(test_label="EL", 
                      mcmc_func_name="mcmc_gp_unn_post_dens_approx", llik_em=lpost_em,
                      par_prior=par_prior_trunc, approx_type="marginal", 
                      n_itr=20000L, itr_start=10000, n_chain=n_chains, 
                      try_parallel=TRUE, cov_prop=cov_prop_init, adjustment="rectified")
mcmc_approx_EL <- do.call(run_mcmc_chains, mcmc_settings)
samp_dt_EL <- mcmc_approx_EL$samp

# plug-in mean.
mcmc_settings <- list(test_label="mean", 
                      mcmc_func_name="mcmc_gp_unn_post_dens_approx", llik_em=lpost_em,
                      par_prior=par_prior_trunc, approx_type="mean", 
                      n_itr=20000L, itr_start=10000, n_chain=n_chains, 
                      try_parallel=TRUE, cov_prop=cov_prop_init, adjustment="rectified")
mcmc_approx_mean <- do.call(run_mcmc_chains, mcmc_settings)
samp_dt_mean <- mcmc_approx_mean$samp

# Combine samples.
mcmc_dt_approx <- combine_samp_dt(samp_dt_mcwmh, samp_dt_EL, samp_dt_mean)
info_dt_approx <- combine_samp_dt(mcmc_approx_mcwmh$info, mcmc_approx_EL$info, 
                                  mcmc_approx_mean$info)

saveRDS(mcmc_dt_approx, file.path(out_dir, "..", "mcmc_dt_approx.rds"))
saveRDS(info_dt_approx, file.path(out_dir, "..", "info_dt_approx.rds"))
```

```{r}
trace_plts <- get_trace_plots(mcmc_dt_approx)
lpost_trace <- get_trace_plots(info_dt_approx, param_type="dens", param_names="llik")

for(plt in trace_plts) plot(plt)
for(plt in lpost_trace) plot(plt)
```

```{r}
mcmc_dt_approx <- mcmc_dt_approx[!((test_label=="mcwmh-joint") & (chain_idx==2L))]
samp_dt_comb <- combine_samp_dt(samp_dt_comb, mcmc_dt_approx)
samp_dt_comb[test_label=="mcwmh-joint", test_label := "E-acc"]

kde_mean_approx <- get_1d_kde_plots(samp_dt_comb, test_label_baseline="exact",
                                    test_labels="mean")
kde_other_approx <- get_1d_kde_plots(samp_dt_comb, test_label_baseline="exact",
                                     test_labels=c("E-acc", "EL"))

for(i in seq_along(kde_mean_approx)) {
  par_name <- names(kde_mean_approx)[i]
  plt <- kde_mean_approx[[i]] + labs(y="density", color="Post Approx")
  plt <- ggformat_journal(plt, remove_title=TRUE, legend_position=c(1,1), 
                          legend.justification=c(1,1))
  plot(plt)
  
  if(write_plots) ggsave(file.path(plt_dir, paste0("kde_mean_approx_", par_name, ".png")))
}

for(i in seq_along(kde_other_approx)) {
  par_name <- names(kde_other_approx)[i]
  plt <- kde_other_approx[[i]] + labs(y="density", color="Post Approx")
  plt <- ggformat_journal(plt, remove_title=TRUE, legend_position=c(1,1), 
                          legend.justification=c(1,1))
  plot(plt)
  
  if(write_plots) ggsave(file.path(plt_dir, paste0("kde_other_approx_", par_name, ".png")))
}
```

# Active Learning

```{r}

grid_prior <- select_mcmc_samp_mat(samp_dt_prior)[1:100, inv_prob$par_names]

acq_maxvar <- function(U) -acq_llik_neg_var_gp(input=U, llik_em=lpost_em, adjustment="rectified")
acq_maxpostvar <- function(U) {
  -acq_llik_neg_var_lik(input=U, llik_em=lpost_em, adjustment="rectified")
}

acq_ivar <- function(U) {
  evaluate_acq_func_vectorized(acq_llik_IVAR_grid_gp, U, lpost_em, grid_points=grid_prior,
                               adjustment="rectified")
}

acq_ievar <- function(U) {
    evaluate_acq_func_vectorized(acq_llik_IEVAR_grid, U, lpost_em, grid_points=grid_prior,
                                 adjustment="rectified")
}

plts_maxvar <- plot_1d_proj(acq_maxvar, input_grids=input_grids)
plts_maxpostvar <- plot_1d_proj(acq_maxpostvar, input_grids=input_grids)
plts_ivar <- plot_1d_proj(acq_ivar, input_grids=input_grids)
plts_ievar <- plot_1d_proj(acq_ievar, input_grids=input_grids)

for(plt in plts_maxvar) plot(plt)
for(plt in plts_maxpostvar) plot(plt)
for(plt in plts_ivar) plot(plt)
for(plt in plts_ievar) plot(plt)

```

```{r}
# Candidate grids.
n_grid <- 1000L

# Prior grid.
grid_prior <- sample_prior(par_prior, n=n_grid)

# Post-approx grid.
grid_mcwmh <- select_mcmc_samp_mat(samp_dt_comb[test_label=="E-acc"], 
                                   param_type="par", thin=5L,
                                   param_names=inv_prob$par_names)
sp_bounds <- as.matrix(par_prior[inv_prob$par_names, c("bound_lower", "bound_upper")])
grid_mcwmh <- support::sp(n=n_grid, p=ncol(grid_mcwmh), 
                          dist.samp=grid_mcwmh, bd=sp_bounds)$sp
colnames(grid_mcwmh) <- inv_prob$par_names

# Prior-approx mix 1.
idx <- sample(1:nrow(grid_mcwmh), size=n_grid/2)
grid_mix_1 <- rbind(grid_prior[idx,], grid_mcwmh[idx,])
```

```{r}
# Baseline for comparison.

# Prior sample.
n_batch <- 100L
batch_prior <- sample_prior(par_prior, n=n_grid)

# Sub-sample current posterior approximation.
```


```{r}
# Preparing for sequential design runs.

# Function used to update GP. Need to make sure to subtract off the mean. Should 
# eventually have this automatically happen in the llikEmulator update function.
true_func <- function(U) {
  if(is.null(dim(U))) U <- matrix(U, nrow=1L, dimnames=list(NULL, inv_prob$par_names))
  llik(U) - mean_func(U)
}

# Error metrics to compute during sequential design.
n_eval <- 1000L
tracking_settings <- list(interval=5L, func_list=list())
prior_eval <- sample_prior(par_prior, n=n_eval)
lpost_prior_eval <- llik(prior_eval) # TODO: temp, using llik for now.
resids_lpost_prior_eval <- lpost_prior_eval - mean_func(prior_eval)

post_eval <- select_mcmc_samp_mat(samp_dt)
post_eval <- post_eval[sample(1:nrow(post_eval), size=n_eval), inv_prob$par_names]
lpost_post_eval <- llik(post_eval) # TODO: same here
resids_lpost_post_eval <- lpost_post_eval - lpost_eki(post_eval)

tracking_settings$func_list$mean_prior <- function(model, ...) {
  dt <- model$calc_lik_approx_pw_err(lpost_prior_eval, approx_type="mean", err_type=c("mse", "mae"),  
                                     input=prior_eval, return_type="data.table", adjustment="rectified")
  dt[, mean(value), by=.(err_type, approx_type)]
}

tracking_settings$func_list$mean_post <- function(model, ...) {
  dt <- model$calc_lik_approx_pw_err(lpost_post_eval, approx_type="mean", err_type=c("mse", "mae"),  
                                     input=post_eval, return_type="data.table", adjustment="rectified")
  dt[, mean(value), by=.(err_type, approx_type)]
}

tracking_settings$func_list$crps_prior <- function(model, ...) {
  mat <- model$emulator_model$calc_pred_func("crps", type="pw", X_new=prior_eval, 
                                             Y_new=matrix(resids_lpost_prior_eval, ncol=1L))
  colMeans(mat)
}

tracking_settings$func_list$crps_post <- function(model, ...) {
  mat <- model$emulator_model$calc_pred_func("crps", type="pw", X_new=post_eval, 
                                             Y_new=matrix(resids_lpost_post_eval, ncol=1L))
  colMeans(mat)
}

```

```{r}
al_results_maxvar <- run_seq_design(llik_em, "llik_neg_var_gp", n_batch=n_batch, 
                                    opt_method="grid", true_func=true_func, 
                                    reoptimize_hyperpar=FALSE, 
                                    tracking_settings=tracking_settings,
                                    candidate_grid=grid_prior, adjustment="rectified")
saveRDS(al_results_maxvar, file.path(out_dir, "al_results_maxvar.rds"))
```

```{r}
al_results_maxvar_mix <- run_seq_design(lpost_em, "llik_neg_var_gp", n_batch=n_batch, 
                                        opt_method="grid", true_func=true_func, 
                                        reoptimize_hyperpar=FALSE, 
                                        tracking_settings=tracking_settings,
                                        candidate_grid=grid_mix_1, adjustment="rectified")
saveRDS(al_results_maxvar_mix, file.path(out_dir, "al_results_maxvar_mix.rds"))
```

```{r}
al_results_maxvarpost_mix <- run_seq_design(lpost_em, "llik_neg_var_lik", n_batch=n_batch, 
                                            opt_method="grid", true_func=true_func, 
                                            reoptimize_hyperpar=FALSE, 
                                            tracking_settings=tracking_settings,
                                            candidate_grid=grid_prior, adjustment="rectified")
saveRDS(al_results_maxvarpost_mix, file.path(out_dir, "al_results_maxvarpost_mix.rds"))
```


```{r}
process_output <- function(results) {
  computed_quantities <- results$tracking_list$computed_quantities
  itrs_str <- names(results$tracking_list$computed_quantities)
  itrs <- sapply(strsplit(itrs_str, split="_", fixed=TRUE), function(x) as.integer(x[2]))
  n_itr <- length(itrs)
  dt <- data.table(itr=itrs,
                   prior_mae = numeric(n_itr),
                   prior_rmse = numeric(n_itr),
                   post_mae = numeric(n_itr),
                   post_rmse = numeric(n_itr))
                   # prior_crps = numeric(n_itr),
                   # post_crps = numeric(n_itr))
  
  for(i in seq_along(itrs)) {
    itr_str <- itrs_str[i]
    q_itr <- computed_quantities[[itr_str]]
    dt[i, `:=`(prior_mae=q_itr$mean_prior[err_type=="mae", V1],
               post_mae=q_itr$mean_post[err_type=="mae", V1],
               prior_rmse=q_itr$mean_prior[err_type=="mse", sqrt(V1)],
               post_rmse=q_itr$mean_post[err_type=="mse", sqrt(V1)])]
               # prior_crps=q_itr$crps_prior,
               # post_crps=q_itr$crps_post)]
  }
  
  dt <- data.table::melt.data.table(dt, id.vars="itr")
  dt[, c("val_data", "metric") := tstrsplit(variable, "_", fixed=TRUE)]
  
  return(dt)
}
```


```{r}
acq_results_maxvar <- process_output(al_results_maxvar)
acq_results_maxvar[, label := "maxvar"]

acq_results_maxvar_mix <- process_output(al_results_maxvar_mix)
acq_results_maxvar_mix[, label := "maxvar_mix"]

acq_results_maxvarpost_mix <- process_output(al_results_maxvarpost_mix)
acq_results_maxvarpost_mix[, label := "maxvarpost_mix"]

acq_results <- rbindlist(list(acq_results_maxvar, acq_results_maxvar_mix, acq_results_maxvarpost_mix))

plt_maxvar_mae <- ggplot(acq_results[metric=="rmse"], aes(x=itr)) + 
                    geom_line(aes(y=value, color=label, linetype=val_data))

plot(plt_maxvar_mae)

plot(1:150, lpost(al_results_maxvar$inputs))
```







